force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>Object to Log Integration Attempts, keeping a record of successes and failures</description>
    <label>Integration Log</label>
    <nameField>
        <label>Integration Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Name__c</fullName>
    <description>Name of Integration</description>
    <label>Integration Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Error Details or notes</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Records_Processed__c.field-meta.xml
<CustomField>
    <fullName>Records_Processed__c</fullName>
    <description>Number of records created/updated</description>
    <label>Records Processed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Run_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Run_Timestamp__c</fullName>
    <description>timestamp for when integration ran.</description>
    <label>Run_Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the success of the integration callout</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExchangeRateScheduler.cls
/**
 * @description Scheduler class to run the exchange rate update on a schedule
 * Scheduling should be done in Salesforce Setup Apex Classes -> Schedule Apex
 */
global class ExchangeRateScheduler implements Schedulable{
    
    /**
     * @description Executes the scheduled job to update exchange rates
     * @param context The SchedulableContext
     */
    global void execute(SchedulableContext sc) {
        // TODO: Implement the method to update exchange rates
        Integration_Log__c logEntry = new Integration_Log__c();
        logEntry.Integration_Name__c = 'ExchangeRateAPI';
        logEntry.Run_Timestamp__c = Datetime.now();
        try{
            List<Exchange_Rate__c> updatedRates = ExchangeRateService.updateExchangeRates();
            logEntry.Status__c = 'Success';
            logEntry.Records_Processed__C = updatedRates.size();
        } catch (Exception e){
            logEntry.Status__c = 'Error';
            logEntry.Message__c = 'Error: ' + e.getMessage();
        }
        insert logEntry;
    }

    /**
     * @description Schedules the job to run at 1 AM daily.
     */

    public static void scheduleJob(){
        String jobName = 'Update Exchange Rates';
        String cronExpression = '0 0 1 * * ?'; // daily at 1:00 AM

        for(CronTrigger ct : [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = :jobName]){
            System.abortJob(ct.Id);  // Avoid duplicate jobs by aborting existing job before scheduling anew
        }

        System.schedule(jobName, cronExpression, new ExchangeRateScheduler());
    }
}